test_app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("web.urls", namespace="web")),
]

web/urls.py
from . import views
from django.urls import path


app_name = "web"

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('add_user/',views.AddUserView.as_view(),name='add_user'),
    path('user_detail/<str:pk>/',views.UserDetailView.as_view(),name='user_detail_view'),
    path('delete/<int:pk>/',views.DeleteUser.as_view(),name='delete_user'),
]

web/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class User(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    place = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('web:user_detail_view', args=[self.pk])

class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField(max_length=500)
    
    user = models.ForeignKey(User,on_delete=models.PROTECT,related_name='posts')
    def __str__(self):
        return self.title


class Publisher(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Author(models.Model):
    name = models.CharField(max_length=100)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE,related_name='authors')

    def __str__(self):
        return self.name
    
class Genre(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author, on_delete=models.CASCADE,related_name='books')
    genre = models.ManyToManyField(Genre,related_name='books')

    def __str__(self):
        return self.title

web/forms.py
from django import forms
from web.models import User



class UserAddForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("name", "place", "email")

web/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView,CreateView, TemplateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from web.models import User
from .forms import UserAddForm
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.http import HttpResponse
# Create your views here.

class IndexView(ListView):
    model = User
    template_name = 'web/index.html'
    context_object_name = 'users'

class AddUserView(CreateView):
    model = User
    template_name = 'web/add_user.html'
    form_class = UserAddForm
    success_url = reverse_lazy('web:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        users = User.objects.all()
        context['users'] = users
        return context


    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            users = User.objects.all()
            context = {'users': users}
            user_list_html = render_to_string('web/user_list.html', context)
            if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                return JsonResponse({'user_list_html': user_list_html})
            else:
                return HttpResponse(user_list_html)
        else:
            if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                return JsonResponse({'success': False, 'errors': form.errors})
            else:
                return self.form_invalid(form)
            
    


class UserDetailView(DetailView):
    model= User
    template_name = 'web/user_detail.html'
    context_object_name = 'user_detail'



class DeleteUser(DeleteView):
    model = User
    success_url = reverse_lazy('web:index')
    template_name = 'web/confirm-delete.html'




#return JsonResponse({'success': True, 'user_list_html': user_list_html})
# def post(self, request):
    #     form = self.form_class(request.POST)
    #     if form.is_valid():
    #         form.save()
    #         users = User.objects.all()
    #         context = {'users': users}
    #         user_list_html = render_to_string('web/user_list.html', context)
    #     if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
    #         print('***'*10)
    #         return JsonResponse({'success': False, 'errors': form.errors})
    #     return HttpResponse(user_list_html)

templates/web/add_user.html
{% extends 'web/base.html' %} 
{% load static crispy_forms_tags  %} 

{% block content %}

<div class="container pt-5">
    <h2>Add New User Here</h2>
</div>

<div class="container pt-5">
    <form method="post" id="add-user-form" >
        {% csrf_token %}
        {{ form|crispy }}
        <div class="form-group pt-2 pb-5">
            <button type="submit" class="btn btn-success js-create-user"><span class="glyphicon glyphicon-ok"></span>Submit</button>
            <a href="{% url 'web:index' %}" class="btn btn-primary">Cancel</a>
        </div>
    </form>

    <div id="user-list-section">
        {% include 'web/user_list.html' %}
    </div>
</div>



<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    $(document).ready(function() {
        $('#add-user-form').submit(function(e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '{% url "web:add_user" %}',
                data: $(this).serialize(),
                success: function(response) {
                    $('#user-list-section').html(response.user_list_html);
                    $('#add-user-form')[0].reset();
                },
                error: function(xhr, status, error) {
                    console.log(error);
                }
            }); 
        });
    });
</script>


{% endblock %}



{% comment %} <script>
    $('#add-user-form').submit(function(e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "web:add_user" %}',
            data: $(this).serialize(),
            success: function(response) {
                $('#user-list-section').html(response.user_list_html);
            },
            error: function(xhr, status, error) {
               
                console.log(error);
            }
        }); 
    });
</script> {% endcomment %}

templates/web/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>CRUD</title>
  </head>
  <body>
    

    {% include 'web/header.html' %}

    {% block content %}
    {% endblock %}

    {% include 'web/footer.html' %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/web/confirm-delete.html
{% extends 'web/base.html' %} 
{% load static %} 

{% block content %}


<div class="container  pt-5 pb-5">

    <form method="post">
        {% csrf_token %}
        <p>Are you sure want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" >
    </form>

</div>


{% endblock %}

templates/web/footer.html
{% load static %}



<!-- Footer -->
<footer class="bg-dark text-center text-white">
    <!-- Grid container -->
    <div class="container p-4">
    
  
      <!-- Section: Form -->
      <section class="">
        <form action="">
          <!--Grid row-->
          <div class="row d-flex justify-content-center">
           
  
           
          </div>
          <!--Grid row-->
        </form>
      </section>
      <!-- Section: Form -->
  
      
  
     
    </div>
    <!-- Grid container -->
  
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2023 Copyright:
      <a class="text-white" href="">developed by </a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

templates/web/header.html
{% load static %}

<header>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'web:index' %}">TEST</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'web:index' %}"> Users List</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'web:add_user' %}">Add New User</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

</header>

templates/web/index.html
{% extends 'web/base.html' %} 
{% load static %} 
{% block content %}


<div class="container px-4 pt-5 pb-5">
    <div class="row gx-5">
      {% for user in users %}
      <div class="col-4">
        <div class="card" style="width: 18rem;">
           
            <div class="card-body">
              <h5 class="card-title" style="color: brown;">{{user.name}}</h5>
              <p class="card-text">{{user.email}}</p>
              <p class="card-text">{{user.place}}</p>
              
              <a href="{{user.get_absolute_url}}" class="btn btn-primary">View</a>
              <a href="" class="btn btn-success">Edit</a>
              <a href="{% url 'web:delete' user.pk %}" class="btn btn-danger">Delete</a>
            </div>
          

        </div>
      </div>
      {% endfor %}
      
      
    </div>
  </div>




{% endblock %}

templates/web/user_detail.html
{% extends 'web/base.html' %} 
{% load static %} 
{% block content %}


<div class="container pt-5 pb-5">
    <div class="card">
        <div class="card-header" style="color: brown;">
            {{user_detail.name}}
        </div>
        <div class="card-body">
        
          <h5 class="card-title pt-2">Place :  {{user_detail.place}}</h5>
          <p class="card-text">Email :  {{user_detail.email}}</p>
          
        </div>
      </div>



</div>









{% endblock %}

templates/web/user_list.html
<div class="container px-4 pt-5 pb-5">
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Place</th>
                <th>Email</th>
                <th>Actions</th>
                
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.name }}</td>
                <td>{{ user.place }}</td>
                <td>{{ user.email }}</td>
                <td>
                    <a href="{{user.get_absolute_url}}"><button class="btn btn-success btn-sm">View</button></a>
                    <a href=""><button class="btn btn-primary btn-sm">Edit</button></a>
                    <a href="{% url 'web:delete_user' user.pk %}"><button class="btn btn-danger btn-sm">Delete</button></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>